### ISSUE TITLE
Is it the current alignment step manually or automatically?

### ISSUE THREAD

**Issue by GabrielLin** [yc9701/pansori#1]
Could you please tell me the current repo use manually or automatically method? Thanks.

**Comment by yc9701** [comment]
Sorry for the late response.
Currently, alignment is done through segmenting the audio file using the timestamps in the subtitle file and then manually aligning through finetuneas. We're currently working on an update that includes automatic alignment through the [Montreal Forced Aligner](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner).
